platform:
  - x64

build: off

install:
  - choco install -y ghc --version 8.4.3
  - choco install -y cabal --version 2.2.0.0
  - refreshenv
  - set PATH=%APPDATA%\cabal\bin;C:\msys64\usr\bin;%PATH%;C:\Program Files\Git\mingw64\bin

environment:
  global:
    MSYSTEM: MINGW64
    NUMBER_OF_PROCESSORS: 1

build_script:
  - git submodule init
  - git submodule update
  - cabal update
  - cp cabal.project.GHC843.freeze cabal.project.freeze
  - cabal new-build

test_script:
  - cabal new-test
