platform:
  - x64

build: off

install:
  - pacman -Suuy --noconfirm
  - pacman -Suuy --noconfirm
  - choco install -y ghc --version 8.2.2
  - refreshenv
  - set PATH=%APPDATA%\cabal\bin;C:\msys64\usr\bin;%PATH%;C:\Program Files\Git\mingw64\bin

environment:
  global:
    MSYSTEM: MINGW64
    NUMBER_OF_PROCESSORS: 1

build_script:
  - cabal update
  - cabal new-build

test_script:
  - cabal new-test
