platform:
  - x64

build: off

install:
  - choco install -y ghc --version 8.2.1
  - refreshenv
  - set PATH=%APPDATA%\cabal\bin;C:\Program Files\Git\mingw64\bin;%PATH%;C:\msys64\usr\bin

environment:
  global:
    MSYSTEM: MINGW64
    NUMBER_OF_PROCESSORS: 1

build_script:
  - cabal update
  - cabal install alex
  - cabal install happy
  - cabal install c2hs
  - cabal new-build

test_script:
  - cabal new-test
