platform:
  - x64

build: off

install:
  - choco install -y ghc --version 8.6.3
  - choco install -y cabal --version 2.4.1.0
  - refreshenv
  - set PATH=%APPDATA%\cabal\bin;C:\msys64\usr\bin;%PATH%;C:\Program Files\Git\mingw64\bin

environment:
  global:
    MSYSTEM: MINGW64
    NUMBER_OF_PROCESSORS: 1

build_script:
  - git submodule update --init --recursive
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

test_script:
  - cabal new-test --enable-tests
