platform:
  - x64

build: off

install:
  - set PATH=C:\Users\appveyor\AppData\Roaming\cabal\bin\;%PATH%;C:\msys64\usr\bin
  - cmd: choco install ghc
  - cmd: choco install cabal

environment:
  global:
    MSYSTEM: MINGW64

build_script:
  - cabal update
  - cabal install alex
  - cabal install happy
  - cabal install c2hs
  - cabal new-build

test_script:
  - cabal new-test
