sudo: true
language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.3

install:
  - ghc --version
  - cabal --version
  - git submodule update --init --recursive
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks --allow-newer

script:
  - cabal new-test --enable-tests --allow-newer

notifications:
  email: false
