dist: trusty
sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

matrix:
  include:
    - env: CABALVER="2.0" GHCVER="8.2.1"
      compiler: ": #GHC 8.2.1"
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.1], sources: [hvr-ghc]}}
    - os: osx
      env: CABALVER="2.0" GHCVER="8.2.1"
      compiler: ": #GHC 8.2.1"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]];
    then
        brew install ghc cabal-install z3;
    fi
  - unset CC
  - export PATH=/opt/ghc/bin:$HOME/.cabal/bin:$PATH

script:
  - cabal update
  - cabal install -j alex
  - cabal install -j happy
  - cabal install -j c2hs
  - cabal new-build
  - cabal new-test
