dist: trusty
sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

matrix:
  include:
    - env: CABALVER="2.2" GHCVER="8.4.3"
      compiler: ": #GHC 8.4.3"
      addons:
        apt:
          packages:
          - cabal-install-2.2
          - ghc-8.4.3
          - libc++-dev
          sources:
          - hvr-ghc
    - os: osx
      env: CABALVER="2.2" GHCVER="8.4.3"
      compiler: ": #GHC 8.4.3"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]];
    then
        brew install ghc cabal-install;
    fi
  - unset CC
  - export PATH=/opt/ghc/bin:$HOME/.cabal/bin:$PATH

script:
  - cp cabal.project.GHC843.freeze cabal.project.freeze
  - git submodule init
  - git submodule update
  - cabal update
  - cabal new-build -j
  - cabal new-test
